"""add confirm column

Revision ID: 08699e15fbae
Revises: 41fc1fcea820
Create Date: 2016-06-24 23:14:10.022328

"""

# revision identifiers, used by Alembic.
revision = '08699e15fbae'
down_revision = '41fc1fcea820'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
